Document: sunxi-mali
Title: Debian sunxi-mali Manual
Author: <insert document author here>
Abstract: This manual describes what sunxi-mali is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sunxi-mali/sunxi-mali.sgml.gz

Format: postscript
Files: /usr/share/doc/sunxi-mali/sunxi-mali.ps.gz

Format: text
Files: /usr/share/doc/sunxi-mali/sunxi-mali.text.gz

Format: HTML
Index: /usr/share/doc/sunxi-mali/html/index.html
Files: /usr/share/doc/sunxi-mali/html/*.html
